WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 11, in <module>
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 11, in <module>
    from src.solver import TASKS
    from src.solver import TASKS
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/__init__.py", line 5, in <module>
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/__init__.py", line 5, in <module>
    from .det_solver import DetSolver
      File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_solver.py", line 18, in <module>
from .det_solver import DetSolver
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_solver.py", line 18, in <module>
    from pytorch_grad_cam import GradCAM, ScoreCAM, GradCAMPlusPlus, AblationCAM, XGradCAM, EigenCAM, FullGrad
    from pytorch_grad_cam import GradCAM, ScoreCAM, GradCAMPlusPlus, AblationCAM, XGradCAM, EigenCAM, FullGrad
ModuleNotFoundError: No module named 'pytorch_grad_cam'
ModuleNotFoundError: No module named 'pytorch_grad_cam'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1837281) of binary: /home/hslee/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/hslee/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-08_19:29:06
  host      : pascal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1837282)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-08_19:29:06
  host      : pascal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1837281)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
