WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Initialized distributed mode...
Start training
Load PResNet50 state_dict
weight_dict: {'loss_vfl': 1, 'loss_bbox': 5, 'loss_giou': 2}
Initial lr:  [1e-05, 0.0001, 0.0001, 0.0001]
loading annotations into memory...
Done (t=8.14s)
creating index...
index created!
loading annotations into memory...
Done (t=0.21s)
creating index...
index created!
number of params: 42862860
Epoch: [0]  [    0/14786]  eta: 6:59:39  lr: 0.000010  loss: 47.0723 (47.0723)  js_div: 2.5534 (2.5534)  loss_w_neck: 44.9483 (44.9483)  loss_bbox: 1.6016 (1.6279)  loss_bbox_aux_0: 1.6280 (1.6484)  loss_bbox_aux_1: 1.6113 (1.6435)  loss_bbox_aux_2: 1.6301 (1.6350)  loss_bbox_aux_3: 1.5827 (1.6247)  loss_bbox_aux_4: 1.5905 (1.6285)  loss_bbox_aux_5: 1.6475 (1.6691)  loss_bbox_dn_0: 0.9616 (0.9651)  loss_bbox_dn_1: 0.9616 (0.9651)  loss_bbox_dn_2: 0.9616 (0.9651)  loss_bbox_dn_3: 0.9616 (0.9651)  loss_bbox_dn_4: 0.9616 (0.9651)  loss_bbox_dn_5: 0.9616 (0.9651)  loss_giou: 1.6697 (1.6803)  loss_giou_aux_0: 1.6757 (1.7002)  loss_giou_aux_1: 1.6312 (1.6648)  loss_giou_aux_2: 1.6601 (1.6881)  loss_giou_aux_3: 1.6509 (1.6755)  loss_giou_aux_4: 1.6439 (1.6725)  loss_giou_aux_5: 1.6717 (1.6898)  loss_giou_dn_0: 1.3402 (1.3554)  loss_giou_dn_1: 1.3402 (1.3554)  loss_giou_dn_2: 1.3402 (1.3554)  loss_giou_dn_3: 1.3402 (1.3554)  loss_giou_dn_4: 1.3402 (1.3554)  loss_giou_dn_5: 1.3402 (1.3554)  loss_vfl: 0.3383 (0.3433)  loss_vfl_aux_0: 0.3373 (0.3391)  loss_vfl_aux_1: 0.3375 (0.3459)  loss_vfl_aux_2: 0.3299 (0.3379)  loss_vfl_aux_3: 0.3358 (0.3424)  loss_vfl_aux_4: 0.3543 (0.3557)  loss_vfl_aux_5: 0.3166 (0.3459)  loss_vfl_dn_0: 0.8051 (0.8245)  loss_vfl_dn_1: 0.8036 (0.8395)  loss_vfl_dn_2: 0.7822 (0.7998)  loss_vfl_dn_3: 0.7993 (0.8215)  loss_vfl_dn_4: 0.8111 (0.8350)  loss_vfl_dn_5: 0.7887 (0.8169)  loss_wo_neck: 44.0893 (44.0893)  time: 1.7030  data: 0.5396  max mem: 6695
Traceback (most recent call last):
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 50, in <module>
    main(args)
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 36, in main
    solver.fit()
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_solver.py", line 40, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_engine.py", line 98, in train_one_epoch
    loss_w_neck_dict = criterion(outputs_w_neck, targets)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/rtdetr_criterion.py", line 299, in forward
    indices = self.matcher(outputs_without_aux, targets)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/matcher.py", line 99, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/box_ops.py", line 54, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 50, in <module>
    main(args)
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/train.py", line 36, in main
    solver.fit()
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_solver.py", line 40, in fit
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/solver/det_engine.py", line 98, in train_one_epoch
    loss_w_neck_dict = criterion(outputs_w_neck, targets)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/rtdetr_criterion.py", line 299, in forward
    indices = self.matcher(outputs_without_aux, targets)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/matcher.py", line 99, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/Backbone-Neck-Self-Distillation/RT-DETR/tools/../src/zoo/rtdetr/box_ops.py", line 54, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1461115) of binary: /home/hslee/anaconda3/bin/python
Traceback (most recent call last):
  File "/home/hslee/anaconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-05_23:22:29
  host      : pascal
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1461116)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-05_23:22:29
  host      : pascal
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1461115)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
